/* auto-generated by NAPI-RS */
/* eslint-disable */
export class FileType {
  constructor(bytes: Uint8Array)
  /**
   * Returns the common extension of the file format.
   *
   * Note: this information is never empty.
   *
   * # Examples
   *
   * Basic usage:
   *
   * ```
   * new FileType([...]).extension() // "wmv"
   *```
   */
  extension(): string
  /**
   * Returns the `Kind` of the file format.
   *
   * # Examples
   *
   * Basic usage:
   *
   * ```
   * new FileType([...]).kind() // Kind.Archive
   *```
   */
  kind(): Kind
  /**
   * Returns the common media type (formerly known as MIME type) of the file format as
   * defined in [IETF RFC 6838](https://tools.ietf.org/html/rfc6838).
   *
   * Note: some media types may not be defined in the
   * [IANA registry](https://www.iana.org/assignments/media-types/media-types.xhtml).
   *
   * # Examples
   *
   * Basic usage:
   *
   * ```
   * new FileType([...]).media_type() // "application/zstd"
   *```
   */
  mime(): string
  /**
   * Returns the full name of the file format.
   *
   * # Examples
   *
   * Basic usage:
   *
   * ```
   * new FileType([...]).name() // "MPEG-1/2 Audio Layer 3"
   *```
   */
  name(): string
}

/** A kind of file format. */
export enum Kind {
  /** Files and directories stored in a single, possibly compressed, archive. */
  Archive = 'Archive',
  /** Musics, sound effects, and spoken audio recordings. */
  Audio = 'Audio',
  /** Compressed single files or streams. */
  Compressed = 'Compressed',
  /** Organized collections of data. */
  Database = 'Database',
  /** Visual information using graphics and spatial relationships. */
  Diagram = 'Diagram',
  /** Floppy disk images, optical disc images and virtual machine disks. */
  Disk = 'Disk',
  /** Word processing and desktop publishing documents. */
  Document = 'Document',
  /** Electronic books. */
  Ebook = 'Ebook',
  /** Machine-executable code, virtual machine code and shared libraries. */
  Executable = 'Executable',
  /** Typefaces used for displaying text on screen or in print. */
  Font = 'Font',
  /** Mathematical formulas. */
  Formula = 'Formula',
  /** Collections of geospatial features, GPS tracks and other location-related files. */
  Geospatial = 'Geospatial',
  /** Animated images, icons, cursors, raster graphics and vector graphics. */
  Image = 'Image',
  /** Data that provides information about other data. */
  Metadata = 'Metadata',
  /** 3D models, CAD drawings, and other types of files used for creating or displaying 3D images. */
  Model = 'Model',
  /** Data which do not fit in any of the other kinds. */
  Other = 'Other',
  /** Collections of files bundled together for software distribution. */
  Package = 'Package',
  /** Lists of audio or video files, organized in a specific order for sequential playback. */
  Playlist = 'Playlist',
  /** Slide shows. */
  Presentation = 'Presentation',
  /** Copies of a read-only memory chip of computers, cartridges, or other electronic devices. */
  Rom = 'Rom',
  /** Data in tabular form. */
  Spreadsheet = 'Spreadsheet',
  /** Subtitles and captions. */
  Subtitle = 'Subtitle',
  /** Moving images, possibly with color and coordinated sound. */
  Video = 'Video'
}

